### ISSUE TITLE
cant do colorcodes

### ISSUE THREAD

**Issue by Goten87** [cranstonide/linux-minecraft-scripts#6]
hello m8 i have somthing for u to test out xD
`screen -p 0 -S minecraft -X eval "stuff \"say backup system starting up.\"\015"`
thats your script and i wanne use a color code in it and it need to be like this
`screen -p 0 -S minecraft -X eval "stuff \"say §3 backup system starting up.\"\015"`
and the text color ingame needs to be a other color then
but then i do it it makes a weird ? in a white box for me

maby u can resolves this bug

btw i use a minecraft forge server
and it needs to work

**Comment by mide** [comment]
This isn't a bug. I never said it would work with a minecraft forge server. 

I will tag this as an enhancement and see if there is something I can do.

**Comment by mide** [comment]
After some review, my code works fine. If you want to add the § character, you'll need to use the ASCII code, `167`. In other words, if you look at `mc-time.sh`, you'll see the following.

```
 screen -p 0 -S minecraft -X eval "stuff \"time set $1\"\015"
```

Let's say we want the output to be bright green. You could change the above line to the following (I haven't checked, but I think it would work)

```
 screen -p 0 -S minecraft -X eval "stuff \"say \167a Time has been changed.\"\015"
```

Notice the `\167a`, this is the escape character plus the hexadecimal character representing the color. I think this should work, but like I said, I haven't tested it.

**Comment by mide** [comment]
I ended up testing it, and it does indeed work, but not how I explained above. Open your file you're trying to edit (for example, `mc-time.sh`.

Copy and paste the section symbol into the `stuff \"...\"` as follows:

```
 screen -p 0 -S minecraft -X eval "stuff \"say Â§a Time has been set to $1.\"\015"
```

When you do, you'll see `Â§` appear, rather than just the section symbol. Add the color code directly next to it like in the example above.

_I did this using Vim inside a PuTTY session, so the characters may look different._
